---
title: "Heart Disease"
author: "The Gene Signature Commons Group"
date: "`r Sys.Date()`"
output:
  html_document
---
Source: https://github.com/markziemann/gene_sig_commons

## Background

This analysis is an example of how gene signatures can be generated from publicly available omics data.
In this example, we will obtain data from the [DEE2](http://dee2.io) database, perform differential analysis with DESeq2 and then return the gene signature. 

```{r,setup}
source("de_functions.R")
```


```{r,study_list,fig.width=8,fig.height=8}
# let's assume species is human for now
SPECIES = "hsapiens"

# read in the file
x <- readLines("Heart Disease.md")

# this is the best way to get studies with contrasts set up
x <- x[grep("RP",x)]

# how many contrasts to do?
length(x)

x1 <- x[[2]]

# prepare by deleting the directory called "gmt"
unlink("gmt", recursive = TRUE)

# lets prototype this by 
#main(x[[2]])

# now go ahead and run the whole thing
data <- sapply(x,main)

# rename the folder
unlink("gmt_heartdisease", recursive = TRUE)
file.rename("gmt","gmt_heartdisease")

# some things are better done with bash :)
system("cat gmt_heartdisease/*gmt > heartdisease.gmt")

unlink("gmt_heartdisease", recursive = TRUE)

```
