---
title: "SRP096177"
author: "Mark Ziemann"
date: "`r Sys.Date()`"
output:
  html_document
---

## Setup pipeline

```{r,setup}
suppressPackageStartupMessages({
    library("SummarizedExperiment")
    library("htm2txt")
    source("https://raw.githubusercontent.com/markziemann/getDEE2/master/R/getDEE2.R")
    library("DESeq2")
    library("edgeR")
    library("gplots") 
})
```

## Study Description

TODO: Define the study design.

```{r,study_info}
SRP = "SRP096177"
SPECIES = "hsapiens"
RUNS <- c("SRR5150592","SRR5150593","SRR5150594","SRR5150595","SRR5150596","SRR5150597")
GROUPS <- factor(c("Set7KD","Set7KD","Set7KD","NTC","NTC","NTC"), 
    levels=c("NTC","Set7KD"),ordered = TRUE)
CONTRASTNAME="Control vs Set7 knock-down"
samplesheet <- as.data.frame(GROUPS,row.names = RUNS)
samplesheet$label <- paste(rownames(samplesheet),samplesheet$GROUPS)
mm <- model.matrix(~GROUPS,samplesheet)
mm
```
## Download

Fetch the dataset from [DEE2](http://dee2.io).

```{r,get}
mdat <- getDee2Metadata(species = SPECIES)
head(mdat)
SRRvec <- mdat[which(mdat$SRP_accession==SRP),1]
x <- getDEE2(SRRvec = SRRvec, species = SPECIES, metadata = mdat, legacy = TRUE)

str(x)
head(x$GeneCounts)

```

## Multidimensional scaling plot

```{r,analysis1}
y <- x$GeneCounts
colnames(y) <- samplesheet$label
head(y)  
nrow(y)
yy <- y[which(rowMeans(y)>10),]
head(yy)
MDS <- function(x,mylabels, ...) {
    mydist <- cmdscale(dist(t(x)))
    myrange <- range(mydist[,1])*1.3
    plot(mydist, xlab="Coordinate 1", ylab="Coordinate 2", 
        type = "n", xlim=myrange, ...)
    text(mydist, labels=mylabels, cex=0.9) 
}
MDS(x = yy, mylabels = samplesheet$label ,main=SRP)

```

## Differential analysis

```{r,de}
dds <- DESeqDataSetFromMatrix(countData = yy,
                              colData = samplesheet,
                              design= mm )
dds <- DESeq(dds)
de <- results(dds)
de <- de[order(de$pvalue),]

# RPM
yyy <- yy/colMeans(yy) * 1000000
res <- cbind(de,yyy,yy)
```

## Charts

```{r,decharts}
# MA plot
sig <-subset(de, padj < 0.05 )
GENESUP <- nrow(subset(sig,  log2FoldChange > 0 ))
GENESDN <- nrow(subset(sig,  log2FoldChange < 0 ))
SUBHEADER = paste(GENESUP, "up, ", GENESDN, "down")
ns <-subset(de, padj > 0.05 )
plot(log2(de$baseMean),de$log2FoldChange, 
     xlab="log2 basemean", ylab="log2 foldchange",
     pch=19, cex=0.5, col="dark gray",
     main=CONTRASTNAME)
points(log2(sig$baseMean),sig$log2FoldChange,
       pch=19, cex=0.5, col="red")
mtext(SUBHEADER)
up <- rownames(subset(de, log2FoldChange>0 & padj<0.05 ))
dn <- rownames(subset(de, log2FoldChange<0 & padj<0.05 ))

# heatmap
top <- yyy[which(rownames(yyy) %in% head(rownames(de),100)),]
head(top)
colfunc <- colorRampPalette(c("blue", "white", "red"))
heatmap.2(  as.matrix(top), col=colfunc(25),scale="row", trace="none",margins = c(6,6), cexRow=.4,
    main=SRP)

```

##  Gene sets
```{r,genesets}
UPNAME = paste(SRP, "up-regulated by knock-down of Setd7 expression")
DOWNNAME = paste(SRP, "down-regulated by knock-down of Setd7 expression")

gs <- list(UPNAME=up,DOWNNAME=dn)
str(gs)
# secure copy
# https://www.rdocumentation.org/packages/ssh/versions/0.6/topics/scp
```

## Session info
```{r,sessioninfo}
sessionInfo()
```