---
title: "Diabetes"
author: "The Gene Signature Commons Group"
date: "`r Sys.Date()`"
output:
  html_document
---
Source: https://github.com/markziemann/gene_sig_commons

## Background

This analysis is an example of how gene signatures can be generated from publicly available omics data.
In this example, we will obtain data from the [DEE2](http://dee2.io) database, perform differential analysis with DESeq2 and then return the gene signature. 

```{r,setup}
source("../de_functions.R")
```


```{r,study_list,fig.width=8,fig.height=8}
# let's assume species is human for now
SPECIES = "hsapiens"

# read in the file
x <- readLines("../contrasts/diabetes.md")

# this is the best way to get studies with contrasts set up
x <- x[grep("RP",x)]

# how many contrasts to do?
length(x)

# get the metadata now to save time
mdat <- getDEE2::getDEE2Metadata(species = SPECIES)

# lets prototype this: main(x[[2]],mdat)

# now go ahead and run the whole thing
data <- lapply(x,function(x) { main(x,mdat) })

lapply(data,length)

data <- data[which(lapply(data,length)>1)]
data <- data[which(lapply(data,function(x) length(x[[5]] ))>0)]
saveRDS(data,"diabetes_data.rds")

gs1 <- lapply(data, function(x) { x[5] })
gs2 <- lapply(data, function(x) { x[6] })
gs <- c(gs1,gs2)
gs <- lapply(gs,function(x) x[[1]] )
gs <- gs[which(lapply(gs,length)==3)]
attributes(gs)$class <- "GMT"
write.GMT(gs,"diabetes_ensemblIDs.gmt")

gs1 <- lapply(data, function(x) { x[7] })
gs2 <- lapply(data, function(x) { x[8] })
gs <- c(gs1,gs2)
gs <- lapply(gs,function(x) x[[1]] )
gs <- lapply(gs,function(x) { x[[3]] <- unique(x[[3]] ) ; return(x) } )
gs <- gs[which(lapply(gs,length)==3)]
attributes(gs)$class <- "GMT"
write.GMT(gs,"diabetes_genesymbols.gmt")


```


```{r,sessioninfo}
sessionInfo()
```
